name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Py 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: makefile
      run: |
        make all

    
